steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  # Deploy
  - name: gcr.io/$_PROJECT_ID/firebase
    args: ["deploy", "--project=$_PROJECT_ID", "--only=hosting"]
