steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  # Deploy
  - name: gcr.io/klimatklockan/firebase
    args: ["deploy", "--project=klimatklockan", "--only=hosting"]
